// <auto-generated />
using System;
using LaGestion.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaGestion.Api.Infrastructure.Migrations
{
    [DbContext(typeof(LaGestionDbContext))]
    [Migration("20260803195912_AppreciationsEtScoring")]
    partial class AppreciationsEtScoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaGestion.Api.Domain.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("siret");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_agencies_slug");

                    b.ToTable("agencies");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTimeOffset?>("ResponseDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_deadline");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_assignments_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_assignments_agency_id");

                    b.HasIndex("ContractorId", "AgencyId")
                        .HasDatabaseName("ix_assignments_contractor_id_agency_id");

                    b.HasIndex("ContractorId", "Status")
                        .HasDatabaseName("ix_assignments_contractor_id_status");

                    b.HasIndex("PositionId", "AgencyId")
                        .HasDatabaseName("ix_assignments_position_id_agency_id");

                    b.HasIndex("PositionId", "ContractorId")
                        .HasDatabaseName("ix_assignments_position_id_contractor_id");

                    b.ToTable("assignments");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly?>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<TimeOnly?>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_availabilities");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_availabilities_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_availabilities_agency_id");

                    b.HasIndex("ContractorId", "AgencyId")
                        .HasDatabaseName("ix_availabilities_contractor_id_agency_id");

                    b.HasIndex("ContractorId", "Date")
                        .HasDatabaseName("ix_availabilities_contractor_id_date");

                    b.HasIndex("ContractorId", "Date", "StartsAt")
                        .IsUnique()
                        .HasDatabaseName("ix_availabilities_contractor_id_date_starts_at");

                    b.ToTable("availabilities");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("BaseCity")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("base_city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DefaultHourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("default_hourly_rate");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("iban");

                    b.Property<string>("InvoicePrefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("invoice_prefix");

                    b.Property<string>("LegalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("legal_status");

                    b.Property<int>("NextInvoiceSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("next_invoice_sequence");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("siret");

                    b.Property<int?>("TravelRadiusKm")
                        .HasColumnType("integer")
                        .HasColumnName("travel_radius_km");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_contractors");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_contractors_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_contractors_agency_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractors_user_id");

                    b.HasIndex("UserId", "AgencyId")
                        .HasDatabaseName("ix_contractors_user_id_agency_id");

                    b.ToTable("contractors");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.ContractorSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contractor_skills");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_contractor_skills_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_contractor_skills_agency_id");

                    b.HasIndex("ContractorId", "AgencyId")
                        .HasDatabaseName("ix_contractor_skills_contractor_id_agency_id");

                    b.HasIndex("ContractorId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_skills_contractor_id_skill_id");

                    b.HasIndex("SkillId", "AgencyId")
                        .HasDatabaseName("ix_contractor_skills_skill_id_agency_id");

                    b.ToTable("contractor_skills");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_key");

                    b.Property<DateOnly?>("IssuedAt")
                        .HasColumnType("date")
                        .HasColumnName("issued_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_documents_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_documents_agency_id");

                    b.HasIndex("AgencyId", "ExpiresAt")
                        .HasDatabaseName("ix_documents_agency_id_expires_at");

                    b.HasIndex("ContractorId", "AgencyId")
                        .HasDatabaseName("ix_documents_contractor_id_agency_id");

                    b.HasIndex("ReviewedByUserId", "AgencyId")
                        .HasDatabaseName("ix_documents_reviewed_by_user_id_agency_id");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessNotes")
                        .HasColumnType("text")
                        .HasColumnName("access_notes");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confidential");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_events_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_events_agency_id");

                    b.HasIndex("AgencyId", "StartsAt")
                        .HasDatabaseName("ix_events_agency_id_starts_at");

                    b.ToTable("events");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_address");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientSiret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("client_siret");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("IssuerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("issuer_address");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer_name");

                    b.Property<string>("IssuerSiret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("issuer_siret");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PdfKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_key");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VatExempt")
                        .HasColumnType("boolean")
                        .HasColumnName("vat_exempt");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_invoices_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_invoices_agency_id");

                    b.HasIndex("AgencyId", "Status")
                        .HasDatabaseName("ix_invoices_agency_id_status");

                    b.HasIndex("ContractorId", "AgencyId")
                        .HasDatabaseName("ix_invoices_contractor_id_agency_id");

                    b.HasIndex("ContractorId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_contractor_id_number");

                    b.HasIndex("ContractorId", "SequenceIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_contractor_id_sequence_index");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hours");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<decimal>("UnitRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_rate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_invoice_lines");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_invoice_lines_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_invoice_lines_agency_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_invoice_id");

                    b.HasIndex("AssignmentId", "AgencyId")
                        .HasDatabaseName("ix_invoice_lines_assignment_id_agency_id");

                    b.HasIndex("InvoiceId", "AgencyId")
                        .HasDatabaseName("ix_invoice_lines_invoice_id_agency_id");

                    b.ToTable("invoice_lines");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.MissionRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<Guid>("RatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_by_user_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mission_ratings");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_mission_ratings_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_mission_ratings_agency_id");

                    b.HasIndex("AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_mission_ratings_assignment_id");

                    b.HasIndex("AssignmentId", "AgencyId")
                        .HasDatabaseName("ix_mission_ratings_assignment_id_agency_id");

                    b.HasIndex("RatedByUserId", "AgencyId")
                        .HasDatabaseName("ix_mission_ratings_rated_by_user_id_agency_id");

                    b.ToTable("mission_ratings");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedup_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_notifications_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_notifications_agency_id");

                    b.HasIndex("AgencyId", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_agency_id_dedup_key");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_notifications_status_created_at");

                    b.HasIndex("UserId", "AgencyId")
                        .HasDatabaseName("ix_notifications_user_id_agency_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("Brief")
                        .HasColumnType("text")
                        .HasColumnName("brief");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DressCode")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dress_code");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Headcount")
                        .HasColumnType("integer")
                        .HasColumnName("headcount");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_positions_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_positions_agency_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_positions_event_id");

                    b.HasIndex("EventId", "AgencyId")
                        .HasDatabaseName("ix_positions_event_id_agency_id");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_refresh_tokens_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_refresh_tokens_agency_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "AgencyId")
                        .HasDatabaseName("ix_refresh_tokens_user_id_agency_id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_revoked_at");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_skills_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_skills_agency_id");

                    b.HasIndex("AgencyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_agency_id_name");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("actual_hours");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("ContractorNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contractor_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("PlannedHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("planned_hours");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<Guid?>("ValidatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("validated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_timesheets");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_timesheets_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_timesheets_agency_id");

                    b.HasIndex("AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_timesheets_assignment_id");

                    b.HasIndex("AssignmentId", "AgencyId")
                        .IsUnique()
                        .HasDatabaseName("ix_timesheets_assignment_id_agency_id");

                    b.HasIndex("ValidatedByUserId", "AgencyId")
                        .HasDatabaseName("ix_timesheets_validated_by_user_id_agency_id");

                    b.ToTable("timesheets");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("Id", "AgencyId")
                        .HasName("ak_users_id_agency_id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_users_agency_id");

                    b.HasIndex("AgencyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_agency_id_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Assignment", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_contractors_contractor_id_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Position", "Position")
                        .WithMany("Assignments")
                        .HasForeignKey("PositionId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_positions_position_id_agency_id");

                    b.Navigation("Contractor");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Availability", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_availabilities_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availabilities_contractors_contractor_id_agency_id");

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Contractor", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contractors_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contractors_users_user_id_agency_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.ContractorSkill", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contractor_skills_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Contractor", "Contractor")
                        .WithMany("Skills")
                        .HasForeignKey("ContractorId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contractor_skills_contractors_contractor_id_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Skill", "Skill")
                        .WithMany("Contractors")
                        .HasForeignKey("SkillId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contractor_skills_skills_skill_id_agency_id");

                    b.Navigation("Contractor");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Document", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Contractor", "Contractor")
                        .WithMany("Documents")
                        .HasForeignKey("ContractorId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_contractors_contractor_id_agency_id");

                    b.HasOne("LaGestion.Api.Domain.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documents_users_reviewed_by_user_id_agency_id");

                    b.Navigation("Contractor");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Event", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_agencies_agency_id");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Invoice", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_contractors_contractor_id_agency_id");

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.InvoiceLine", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_lines_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invoice_lines_assignments_assignment_id_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_lines_invoices_invoice_id_agency_id");

                    b.Navigation("Assignment");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.MissionRating", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mission_ratings_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mission_ratings_assignments_assignment_id_agency_id");

                    b.HasOne("LaGestion.Api.Domain.User", "RatedBy")
                        .WithMany()
                        .HasForeignKey("RatedByUserId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mission_ratings_users_rated_by_user_id_agency_id");

                    b.Navigation("Assignment");

                    b.Navigation("RatedBy");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Notification", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id_agency_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Position", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Event", "Event")
                        .WithMany("Positions")
                        .HasForeignKey("EventId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_events_event_id_agency_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id_agency_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Skill", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_skills_agencies_agency_id");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Timesheet", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_timesheets_agencies_agency_id");

                    b.HasOne("LaGestion.Api.Domain.Assignment", "Assignment")
                        .WithOne("Timesheet")
                        .HasForeignKey("LaGestion.Api.Domain.Timesheet", "AssignmentId", "AgencyId")
                        .HasPrincipalKey("LaGestion.Api.Domain.Assignment", "Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_timesheets_assignments_assignment_id_agency_id");

                    b.HasOne("LaGestion.Api.Domain.User", "ValidatedBy")
                        .WithMany()
                        .HasForeignKey("ValidatedByUserId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_timesheets_users_validated_by_user_id_agency_id");

                    b.Navigation("Assignment");

                    b.Navigation("ValidatedBy");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.User", b =>
                {
                    b.HasOne("LaGestion.Api.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_agencies_agency_id");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Assignment", b =>
                {
                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Contractor", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Event", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Position", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("LaGestion.Api.Domain.Skill", b =>
                {
                    b.Navigation("Contractors");
                });
#pragma warning restore 612, 618
        }
    }
}
